spammer/Logs/urls.py
from django.urls import path

from .apps import LogsConfig
from .views import LogsListView

app_name = LogsConfig.name

urlpatterns = [
    path('', LogsListView.as_view(), name='list'),
]

spammer/spammer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls'), name='users'),
    path('clients/', include('clients.urls'), name='clients'),
    path('messages/', include('message.urls'), name='message'),
    path('SetSending/', include('SetSending.urls'), name='SetSending'),
    path('logs/', include('Logs.urls'), name='Logs')
]

spammer/Logs/models.py
from django.db import models

from SetSending.models import SetSending
from spammer.settings import NULLABLE


class Logs(models.Model):
    time = models.DateTimeField(auto_now_add=True, verbose_name="время последней попытки")
    job = models.ForeignKey(SetSending, on_delete=models.CASCADE, verbose_name='Рассылка')
    status = models.SmallIntegerField(default=0, verbose_name="статус попытки")
    description = models.TextField(verbose_name="ответ почтового сервера", **NULLABLE)

    def __str__(self):
        return f"{self.time} - ({self.status}): {self.description}"

    class Meta:
        verbose_name = "Log"

spammer/Logs/views.py
from django.views.generic import ListView

from Logs.models import Logs


class LogsListView(ListView):
    model = Logs
    ordering = ['pk']

spammer/Logs/templates/Logs/Logs_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/log.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Журнал рассылки</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div>
            <form method="post" enctype="multipart/form-data">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th class="col-1 text-secondary">Код</th>
                        <th class="col-1 text-secondary">Время рассылки</th>
                        <th class="col-4 text-secondary">Рассылка</th>
                        <th class="col-2 text-secondary">Статус</th>
                        <th class="col-4 text-secondary">Описание</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in logs_list %}
                    <tr>
                        <th scope="row">{{ item.pk }}</th>
                        <td > {{ item.time }}</td>
                        <td >{{ item.job }}</td>
                        <td >{{ item.status }}</td>
                        <td >{{ item.description }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </form>
        </div>
</main>

{% endblock %}