spammer/Logs/urls.py
from django.urls import path

from .apps import LogsConfig
from .views import LogsListView

app_name = LogsConfig.name

urlpatterns = [
    path('', LogsListView.as_view(), name='list'),
]

spammer/clients/urls.py
from django.urls import path
from clients.apps import ClientsConfig
from clients.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
]

spammer/spammer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls'), name='users'),
    path('clients/', include('clients.urls'), name='clients'),
    path('messages/', include('message.urls'), name='message'),
    path('SetSending/', include('SetSending.urls'), name='SetSending'),
    path('logs/', include('Logs.urls'), name='Logs')
]

spammer/clients/models.py
from django.db import models
from spammer.settings import NULLABLE
from users.models import User


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name="email адрес")
    name = models.CharField(max_length=150, verbose_name="ФИО")
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    user = models.ForeignKey(User,  on_delete=models.DO_NOTHING, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.name} ({self.email})"

    class Meta:
        verbose_name = "Клиент рассылки"
        verbose_name_plural = "Клиенты рассылки"

spammer/clients/forms.py
from django import forms
from clients.models import Client
from spammer.services import StyleFormMixin


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = ['name', 'email', 'comment']

spammer/clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from clients.forms import ClientForm
from clients.models import Client


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    ordering = ['pk']

    def get_queryset(self):
        # Фильтрация данных модели
        queryset = super().get_queryset()
        filtered_data = queryset.filter(user_id=self.request.user.pk)
        return filtered_data


class ClientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:list')
    success_message = "Данные нового клиента успешно сохранены!"

    def form_valid(self, form):
        new_client = form.save(commit=False)
        new_client.user = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:list')
    success_message = "Данные клиента успешно обновлены!"

    def form_valid(self, form):
        new_client = form.save(commit=False)
        new_client.save()
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('clients:list')
    success_message = "Клиент был успешно удален!"

spammer/clients/templates/clients/client_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-danger bg-gradient">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/user.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Удаление клиента</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        <div style="color: #999999">Наименование:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ client.name }}</h6>
                    </div>
                </div>
                                    <p></p>
                <div class="row">
                    <div class="col-2">
                        <div style="color: #999999">Электронный адрес:</div>
                    </div>
                    <div class="col-8">
                        <h6 style="color: #96cfed;">{{ client.email }}</h6>
                    </div>
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'clients:list' %}" class="btn btn-warning">Отмена</a>
            </div>

        </form>
    </div>
</main>

{% endblock %}

spammer/clients/templates/clients/client_form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/user.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Ввод / редактирование клиента</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-block btn-success">
                Создать / Сохранить
            </button>
        </form>
    </div>

</main>

{% endblock %}

spammer/clients/templates/clients/client_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/user.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Клиенты</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div>
            <form method="post" enctype="multipart/form-data">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th class="col-1 text-secondary">Код</th>
                        <th class="col-4 text-secondary">Наименование</th>
                        <th class="col-3 text-secondary">Электронный адрес</th>
                        <th class="col-5 text-secondary">Комментарий</th>
                        <th class="col-2 text-secondary">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for client in client_list %}
                    <tr>
                        <th scope="row">{{ client.pk }}</th>
                        <td > {{ client.name }}</td>
                        <td style="color: #96cfed;">{{ client.email }}</td>
                        <td >{{ client.comment|slice:45 }}</td>
                        <td>

                            <div class="btn-group btn-group-sm" role="group">
                                {% if perms.clients.change_client %}
                                <button type="button" class="btn btn-warning"
                                        onclick="location.href='{% url 'clients:update' client.pk %}'">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-pencil-square" viewBox="0 0 16 16">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                        <path fill-rule="evenodd"
                                              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                    </svg>
                                </button>
                                {% endif %}
                                {% if perms.clients.delete_client %}
                                <button type="button" class="btn btn-danger"
                                        onclick="location.href='{% url 'clients:delete' client.pk %}'">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-x-circle" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"></path>
                                    </svg>
                                </button>
                                {% endif %}
                            </div>

                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </form>
        </div>
        {% if perms.clients.add_client %}
        <button type="submit" class="btn btn-block btn-primary"
                onclick="location.href='{% url 'clients:create' %}'">
            Добавить клиента
        </button>
        {% endif %}
</main>

{% endblock %}