spammer/Logs/urls.py
from django.urls import path

from .apps import LogsConfig
from .views import LogsListView

app_name = LogsConfig.name

urlpatterns = [
    path('', LogsListView.as_view(), name='list'),
]

spammer/SetSending/urls.py
from django.urls import path
from SetSending.apps import SetsendingConfig
from SetSending.views import SetSendingListView, SetSendingDeleteView, add_sending, edit_sending

app_name = SetsendingConfig.name

urlpatterns = [
    path('', SetSendingListView.as_view(), name='list'),
    path('create/', add_sending, name='create'),
    # path('create/', SetSendingCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', edit_sending, name='update'),
    path('delete/<int:pk>/', SetSendingDeleteView.as_view(), name='delete'),
]

spammer/spammer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls'), name='users'),
    path('clients/', include('clients.urls'), name='clients'),
    path('messages/', include('message.urls'), name='message'),
    path('SetSending/', include('SetSending.urls'), name='SetSending'),
    path('logs/', include('Logs.urls'), name='Logs')
]

spammer/SetSending/models.py
from django.db import models

from clients.models import Client
from message.models import Message
from users.models import User


class SetSending(models.Model):
    time_start = models.DateTimeField(verbose_name="время начала рассылки")
    interval = models.PositiveIntegerField(default=0, verbose_name="интервал рассылки в секундах")
    time_end = models.DateTimeField(verbose_name="время окончания рассылки")
    status = models.PositiveSmallIntegerField(default=1, verbose_name="статус рассылки")
    client = models.ManyToManyField(Client)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="сообщение")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")

    def __str__(self):
        return (f"Старт: {self.time_start}, Интервал: {self.interval} (сек.), Окончание: {self.time_end}, "
                f"Статус: {self.status}")

    class Meta:
        verbose_name = "Настройка рассылки"
        verbose_name_plural = "Настройки рассылки"

spammer/SetSending/forms.py
from django import forms

from SetSending.models import SetSending


class SetSendingForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = SetSending
        fields = ['time_start', 'time_end', 'interval', 'status', 'client', 'message']

spammer/SetSending/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DeleteView
from SetSending.models import SetSending
from clients.models import Client
from message.models import Message
from spammer.services import JobService, Status
from spammer.settings import INTERVALS
from datetime import datetime, timedelta


class SetSendingListView(LoginRequiredMixin, ListView):
    model = SetSending
    ordering = ['pk']

    def get_queryset(self):
        # Фильтрация данных модели
        queryset = super().get_queryset()
        filtered_data = queryset.filter(user_id=self.request.user.pk)
        return filtered_data


class SetSendingDeleteView(LoginRequiredMixin,  DeleteView):
    model = SetSending
    success_url = reverse_lazy('SetSending:list')


@login_required
def add_sending(request):
    """
    Процедура ввода новой рассылки
    :param request:
    """
    dataset = SetSending()

    dataset.time_start = datetime.now()
    dataset.time_end = dataset.time_start + timedelta(days=1)

    client_list = Client.objects.filter(user=request.user.pk)

    list_message = Message.objects.filter(user=request.user.pk)

    if request.method == 'POST':
        set_data(request, dataset)
        dataset.user = request.user

        time_delta = (dataset.time_end - dataset.time_start).total_seconds()

        if time_delta >= float(dataset.interval):
            dataset.save()

            save_select_client(request, dataset)  # сохраняем выбранных клиентов

            if dataset.status == Status.Running:
                jobs = JobService()
                jobs.add_job(request, dataset)

            messages.add_message(request, messages.SUCCESS, f'Данные #{dataset.pk} успешно сохранены!')

            return redirect(reverse('SetSending:list'))
        else:
            messages.add_message(request, messages.ERROR, 'Задание имеет неверное значение периода!')

    data = {'interval': dataset.interval,
            'status': dataset.status,
            'time_start': dataset.time_start,
            'time_end': dataset.time_end,
            'interval_list': INTERVALS,
            'status_list': Status.rus_list,
            'list_message': list_message,
            'client_list': client_list,
            }
    return render(request, 'SetSending/SetSending_form_new.html', data)


@login_required
def edit_sending(request, pk):
    """
    Процедура обновления данных рассылки
    :param request:
    :param pk: ключ записи
    """

    dataset = SetSending.objects.get(id=pk)

    client_list_temp = Client.objects.filter(user=request.user.pk)
    client_list_use = dataset.client.all()

    client_list = list(set(client_list_temp) - set(client_list_use))

    list_message = Message.objects.filter(user=request.user.pk)

    if request.method == 'POST':

        set_data(request, dataset)

        time_delta = (dataset.time_end - dataset.time_start).total_seconds()

        if time_delta >= float(dataset.interval):
            dataset.save()

            save_select_client(request, dataset)  # сохраняем выбранных клиентов

            jobs = JobService()
            if dataset.status == Status.Running:
                jobs.add_job(request, dataset)

            messages.add_message(request, messages.SUCCESS, f'Данные #{dataset.pk} успешно сохранены!')
            return redirect(reverse('SetSending:list'))
        else:
            messages.add_message(request, messages.ERROR, f'Задание имеет неверное значение периода!')

    data = {'interval': int(dataset.interval),
            'time_start': dataset.time_start,
            'time_end': dataset.time_end,
            'status': int(dataset.status),
            'list_message': list_message,
            'interval_list': INTERVALS,
            'status_list': Status.rus_list,
            'id_message': int(dataset.message_id),
            'client_list': client_list,
            'clients': dataset.client
            }

    return render(request, 'SetSending/SetSending_form_new.html', context=data)


def set_data(request, dataset):
    dataset.time_start = datetime.strptime(request.POST.get('time_start'), "%Y-%m-%dT%H:%M")
    dataset.time_end = datetime.strptime(request.POST.get('time_end'), "%Y-%m-%dT%H:%M")
    dataset.status = int(request.POST.get('status_list'))
    dataset.message_id = int(request.POST.get('list_message'))
    dataset.interval = int(request.POST.get('interval_list'))
    dataset.list_address = request.POST.get("list_address")


def save_select_client(request, dataset):
    """
    Процедура сохраняет выбранных клиентов
    :param request:
    :param dataset:
    :return:
    """
    selected_clients = request.POST.getlist('client_list_select')
    dataset.client.clear()
    for item in selected_clients:
        cl = Client.objects.get(id=item)
        dataset.client.add(cl)
        dataset.save()

spammer/SetSending/templates/SetSending/SetSending_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-danger bg-gradient">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/setting.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Удаление рассылки</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col-3">
                        <div style="color: #999999">Код:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ setsending.pk }}</h6>
                    </div>
                </div>
                <p></p>
                <div class="row">
                    <div class="col-3">
                        <div style="color: #999999">Время начала рассылки:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ setsending.time_start }}</h6>
                    </div>
                </div>
                <p></p>
                <div class="row">
                    <div class="col-3">
                        <div style="color: #999999">Время окончания рассылки:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ setsending.time_end }}</h6>
                    </div>
                </div>
                <p></p>
                <div class="row">
                    <div class="col-3">
                        <div style="color: #999999">Интервал:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ setsending.interval }} сек.</h6>
                    </div>
                </div>
                <p></p>
                <div class="row">
                    <div class="col-3">
                        <div style="color: #999999">Сообщение:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ setsending.message }}</h6>
                    </div>
                </div>
                <p></p>
                <div class="row">
                    <div class="col-3">
                        <div style="color: #999999">Статус:</div>
                    </div>
                    <div class="col-8">
                        <h6>{{ setsending.status }}</h6>
                    </div>
                </div>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'SetSending:list' %}" class="btn btn-warning">Отмена</a>
            </div>

        </form>
    </div>
</main>

{% endblock %}

spammer/SetSending/templates/SetSending/SetSending_form_new.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/setting.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Ввод / редактирование рассылки сообщения</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container" style="height: 450px">
                <div class="row" style="height: 100px">
                    <div style="width: 280px;">
                        <label>Начальная дата и время:"</label>
                        <input type="datetime-local" name="time_start" value="{{ time_start|date:'Y-m-d\TH:i' }}">
                    </div>
                    <div style="width: 280px;">
                        <label>Конечная дата и время:</label>
                        <input type="datetime-local" name="time_end" value="{{ time_end|date:'Y-m-d\TH:i' }}">
                    </div>
                    <div style="width: 400px;">
                        <div class="row">
                            <label>Интервал: </label>
                        </div>
                        <div class="row">
                            <select class="col-7" name="interval_list">
                                {% for item in interval_list %}
                                {% if item.value == interval %}
                                <option value="{{ item.value }}" selected>{{ item.text }}</option>
                                {% else %}
                                <option value="{{ item.value }}">{{ item.text }}</option>
                                {% endif%}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row" style="height: 50px">
                    <div style="width: 870px;">
                        <label class="col-2">Статус:</label>
                        <select class="col-7" name="status_list">
                            {% for item in status_list %}
                            {% if item.value == status %}
                            <option value="{{ item.value }}" selected>{{ item.text }}</option>
                            {% else %}
                            <option value="{{ item.value }}">{{ item.text }}</option>
                            {% endif%}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="row">

                            <div class="row ">
                                <div class="col-5 " >
                                    <label>Общий список клиентов:</label>
                                    <select multiple name="client_list" id="client_list" style="width:500px; height:180px ">
                                      {% for client_l in client_list %}
                                            <option value="{{ client_l.pk }}">{{ client_l }}</option>
                                      {% endfor %}
                                    </select>
                                </div>
                                <div style="width: 80px">
                                        <div class="row" style="height:50px"></div>
                                    <div>
                                        <a href="#" class="btn btn-secondary" style="height: 50px; width: 50px"
                                           onclick="moveItems('client_list', 'client_list_select'); return false;">
                                            <svg >
                                                <image href="{% static 'icon/right.png' %}" y="5" width="24" height="24"/>
                                            </svg>
                                        </a>
                                    </div>
                                    <p></p>
                                    <div>
                                        <a href="#" class="btn btn-secondary" style="height: 50px; width: 50px"
                                           onclick="moveItems('client_list_select', 'client_list'); return false;">
                                             <svg >
                                                <image href="{% static 'icon/left.png' %}" y="5" width="24" height="24"/>
                                            </svg>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-5" >
                                    <label>Cписок выбранных клиентов:</label>
                                    <select multiple name="client_list_select" id="client_list_select" style="width:500px; height:180px ">
                                      {% for client_s in clients.all %}
                                            <option value="{{ client_s.pk }}">{{ client_s }}</option>
                                      {% endfor %}
                                  </select>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <p></p>
                        <div class="row">
                            <label class="col-2">Сообщение:</label>
                            <select class="col-8" name="list_message">
                                {% for item in list_message %}
                                {% if item.id == id_message %}
                                <option value="{{ item.pk }}" selected>{{ item.subject }} - {{ item.message }}</option>
                                {% else %}
                                <option value="{{ item.pk }}">{{ item.subject }} - {{ item.message }}</option>
                                {% endif%}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <p></p>
                </div>
            </div>

            <button type="submit" class="btn btn-block btn-success" href="">
                Создать / Сохранить
            </button>
        </form>
    </div>

</main>
<script>
  function moveItems(from, to) {
    var selectFrom = document.getElementById(from);
    var selectTo = document.getElementById(to);

    for (var i = 0; i < selectFrom.options.length; i++) {
      if (selectFrom.options[i].selected) {
        selectTo.appendChild(selectFrom.options[i]);
        i--; // Уменьшаем счетчик, так как элементы сдвигаются влево после удаления
      }
    }
  }
</script>
{% endblock %}

spammer/SetSending/templates/SetSending/SetSending_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load filters_set %}
<main class="form-signin">
    <div class="p-4 p-md-3 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="50" height="60" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                            <image href="{% static 'icon/setting.png' %}" x="0" y="0" width="50" height="60"/>
                        </svg>
                    </div>
                </div>
                <div class="col-10">
                    <div>
                        <h6 class="display-6 fst-italic">Рассылка</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div>
            <form method="post" enctype="multipart/form-data">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th class="col-1 text-secondary">Код</th>
                        <th class="col-2 text-secondary">Время начала рассылки</th>
                        <th class="col-2 text-secondary">Время окончания рассылки</th>
                        <th class="col-1 text-secondary">Интервал</th>
                        <th class="col-2 text-secondary">Список получателей</th>
                        <th class="col-5 text-secondary">Письмо</th>
                        <th class="col-1 text-secondary">Статус</th>
                        <th class="col-2 text-secondary">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for sets in setsending_list %}
                    <tr >
                        <th scope="row">{{ sets.pk }}</th>
                        <td > {{ sets.pk|date_start }}</td>
                        <td >{{ sets.pk|date_end }}</td>
                        <td >{{ sets.pk|interval_text }}</td>
                        <td style="color: #96cfed;">{{ sets.list_address }}</td>
                        <td >{{ sets.message }}</td>
                        <td class="{{ sets.pk|color_status }}">{{ sets.pk|status_text }}</td>
                        <td>
                            {% if perms.SetSending.change_SetSending %}
                            <div class="btn-group btn-group-sm" role="group">
                                <button type="button" class="btn btn-warning"
                                        onclick="location.href='{% url 'SetSending:update' sets.pk %}'">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-pencil-square" viewBox="0 0 16 16">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                        <path fill-rule="evenodd"
                                              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                    </svg>
                                </button>
                                {% endif %}
                                {% if perms.SetSending.delete_SetSending %}
                                <button type="button" class="btn btn-danger"
                                        onclick="location.href='{% url 'SetSending:delete' sets.pk %}'">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-x-circle" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"></path>
                                    </svg>
                                </button>
                            </div>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </form>
        </div>
        {% if perms.SetSending.change_SetSending %}
        <button type="submit" class="btn btn-block btn-primary"
                onclick="location.href='{% url 'SetSending:create' %}'">
            Новая рассылка
        </button>
        {% endif %}
</main>

{% endblock %}